import { Inter } from "next/font/google";
import "./globals.css";

import TransitionProvaider from "@/components/transitionProvaider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransitionProvaider>
          {children}
        </TransitionProvaider>
      </body>
    </html>
  );
}
